In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Comment this if the data visualisations doesn't work on your side
%matplotlib inline

plt.style.use('bmh')

In [2]:
df_real_estate = pd.read_csv("data/20200123_apts_buy_berlin_v0.4_CB.csv", sep=";")

In [4]:
df_real_estate.head()

,Unnamed: 0,id,title,city,quarter,postcode,street,houseNo,price,qm,n_room,latitude,longitude,privateOffer,marketingType,hasCourtage,n_page_is24,price_per_qm
0,0,114366270,Altersgerechtes Wohnen im Viktoria Quartier! 2...,Berlin,Kreuzberg (Kreuzberg),10965,NaN,NaN,398000.0,66.00,2.0,NaN,NaN,False,PURCHASE,YES,1,6030.3
1,1,115294582,EXKLUSIVE NEUBAU-WOHNUNG \nIN RUHIGER KU´DAMM-...,Berlin,Wilmersdorf (Wilmersdorf),10711,NaN,NaN,770000.0,96.59,3.0,NaN,NaN,False,PURCHASE,YES,1,7971.8
2,2,114579519,Wohnen am Bergmannkiez: Moderne 2-Zimmer-Wohnu...,Berlin,Kreuzberg (Kreuzberg),10961,Baruther Straße,5,352000.0,61.80,2.0,52.49401,13.38979,False,PURCHASE,NO,1,5695.8
3,3,114579517,Wohnen im Neubau: Moderne 2-Zimmer-Wohnung mit...,Berlin,Kreuzberg (Kreuzberg),10961,Baruther Straße,5,407000.0,51.42,2.0,52.49401,13.38979,False,PURCHASE,NO,1,7915.2
4,4,114579516,Großes Schlafzimmer und Loggia: Gemütliche 2-Z...,Berlin,Kreuzberg (Kreuzberg),10961,Baruther Straße,5,410000.0,59.34,2.0,52.49401,13.38979,False,PURCHASE,NO,1,6909.3

In [6]:
df_real_estate.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6755 entries, 0 to 6754
Data columns (total 18 columns):
Unnamed: 0       6755 non-null int64
id               6755 non-null int64
title            6755 non-null object
city             6755 non-null object
quarter          6755 non-null object
postcode         6755 non-null int64
street           3615 non-null object
houseNo          3615 non-null object
price            6755 non-null float64
qm               6755 non-null float64
n_room           6755 non-null float64
latitude         3607 non-null float64
longitude        3607 non-null float64
privateOffer     6755 non-null bool
marketingType    6755 non-null object
hasCourtage      6755 non-null object
n_page_is24      6755 non-null int64
price_per_qm     6749 non-null float64
dtypes: bool(1), float64(6), int64(4), object(7)
memory usage: 903.9+ KB

In [8]:
# df.count() does not include NaN values
df2 = df_real_estate[[column for column in df_real_estate if df_real_estate[column].count() / len(df_real_estate) >= 0.3]]

print("List of dropped columns:", end=" ")
for c in df_real_estate.columns:
    if c not in df2.columns:
        print(c, end=", ")
print('\n')
#df = df2

KeyError: 'Id'